FROM node:16-alpine3.14

ENV DATABASE_URL=DATABASE_URL
ENV DATABASE_USER=DATABASE_USER
ENV DATABASE_PASSWORD=DATABASE_PASSWORD
ENV DATABASE_NAME=DATABASE_NAME
ENV REDIS_URL=REDIS_URL
ENV FRONT_PORT=FRONT_PORT
ENV ACCESS_TOKEN_SECRET_KEY=ACCESS_TOKEN_SECRET_KEY
ENV ACCESS_TOKEN_EXPIRE_TIME=ACCESS_TOKEN_EXPIRE_TIME
ENV REFRESH_TOKEN_SECRET_KEY=REFRESH_TOKEN_SECRET_KEY
ENV REFRESH_TOKEN_EXPIRE_TIME=REFRESH_TOKEN_EXPIRE_TIME
ENV EMAIL_VERIFY_TOKEN_SECRET_KEY=EMAIL_VERIFY_TOKEN_SECRET_KEY
ENV EMAIL_VERIFY_TOKEN_EXPIRE_TIME=EMAIL_VERIFY_TOKEN_EXPIRE_TIME
ENV HASH_SALT_ROUNDS=HASH_SALT_ROUNDS
ENV KAKAO_CLIENT_ID=KAKAO_CLIENT_ID
ENV KAKAO_REDIRECT_URI=KAKAO_REDIRECT_URI

WORKDIR /usr/src/app

RUN NODE_ENV=production

COPY . /usr/src/app

RUN npm install

COPY . .

RUN npm run build

CMD ["node", "dist/src/server.js"]
