name: Publish Docker image
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_BUILD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            PROD_REDIS_URL=${{ secrets.PROD_REDIS_URL }}
            FRONT_PORT=${{ secrets.FRONT_PORT }}
            ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
            ACCESS_TOKEN_EXPIRE_TIME=${{ secrets.ACCESS_TOKEN_EXPIRE_TIME }}
            REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
            REFRESH_TOKEN_EXPIRE_TIME=${{ secrets.REFRESH_TOKEN_EXPIRE_TIME }}
            EMAIL_VERIFY_TOKEN_SECRET_KEY=${{ secrets.EMAIL_VERIFY_TOKEN_SECRET_KEY }}
            EMAIL_VERIFY_TOKEN_EXPIRE_TIME=${{ secrets.EMAIL_VERIFY_TOKEN_EXPIRE_TIME }}
            HASH_SALT_ROUNDS=${{ secrets.HASH_SALT_ROUNDS }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AWS_SES_SENDER=${{ secrets.AWS_SES_SENDER }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            S3_REGION=${{ secrets.S3_REGION }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_PROD_CHANNEL_ID=${{ secrets.DISCORD_PROD_CHANNEL_ID }}
            DISCORD_DEV_CHANNEL_ID=${{ secrets.DISCORD_DEV_CHANNEL_ID }}
            MAIL_SERVICE=${{ secrets.MAIL_SERVICE }}
            MAIL_ID=${{ secrets.MAIL_ID }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            MAIL_SENDER=${{ secrets.MAIL_SENDER }}
            LOG_PATH=${{ secrets.LOG_PATH }}

  code-deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Access to server and Run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd docker-server
            docker-compose down
            docker rmi ${{ secrets.IMAGE_NANE }} 
            docker pull ${{ secrets.IMAGE_NANE }} 
            docker-compose up -d
