name: Deploy to GitHub Packages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v3
      # Reference a specific version
      - uses: actions/checkout@v3.2.0
      # Reference a branch
      - uses: actions/checkout@main
        with:
          node-version: '16' 
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
